CREATE TABLE IF NOT EXISTS directions (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    min_score INTEGER NOT NULL
);
ALTER TABLE directions 
ADD COLUMN IF NOT EXISTS total_seats INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS is_closed BOOLEAN NOT NULL DEFAULT FALSE;